/**
 * Admin panel: login, dashboard analytics, orders, products, combos, inventory, Excel export, invoice.
 */
/* ADMIN */
function renderA(pg){if(!adm){$('#app').innerHTML=`<div class="sec lg"><div class=logo><img class=brand src="assets/images/logo.webp" alt="VSD Admin" style="height:78px;margin:0 auto"></div><label>Username</label><input id=au value=admin><label>Password</label><input id=ap type=password><p><button class=btn style=width:100% onclick=login()>Sign in</button></p><p><a onclick=go('') style=cursor:pointer>← Back to store</a></p></div>`;return}
if(D.stale!==0){D.stale=0;$('#app').innerHTML='<p style="padding:30px">Loading…</p>';loadAdmin().then(()=>render()).catch(()=>{adm=false;render()});return}
const M=[['dash','📊 Dashboard'],['orders','📦 Orders'],['prods','🛍️ Products'],['combos','🧺 Combos'],['inv','📋 Inventory'],['theme','🎨 Theme'],['banners','🖼️ Banners'],['settings','⚙️ Settings']];
const fn={dash:aDash,orders:aOrders,prods:aProds,combos:aCombos,inv:aInv,theme:aTheme,banners:aBanners,settings:aSettings}[pg]||aDash;
$('#app').innerHTML=`<div class=adm><div class=sb><div class=logo><img class=brand src="assets/images/logo.webp" alt="VSD Admin" style="height:78px;margin:0 auto"></div>${M.map(m=>`<a class="${pg==m[0]?'on':''}" onclick="go('admin/${m[0]}')">${m[1]}</a>`).join('')}<a onclick="go('')">🌐 View store</a><a onclick="logout()">🚪 Logout</a></div><div class=ct>${fn()}</div></div>`}
function login(){api('/api/admin/login',{method:'POST',body:{user:$('#au').value,password:$('#ap').value}}).then(()=>{adm=true;D.stale=1;go('admin/dash')}).catch(e=>toast(e.message))}
function logout(){api('/api/admin/logout',{method:'POST'}).finally(()=>{adm=false;D.orders=[];D.stale=1;go('admin')})}
const live=()=>D.orders.filter(o=>o.st!='Cancelled'),inR=(o,d)=>new Date(o.d)>=new Date(Date.now()-d*864e5);
function aDash(){const os=D.orders.filter(o=>inR(o,R)),lv=os.filter(o=>o.st!='Cancelled'),rev=lv.reduce((a,o)=>a+o.tot,0),td=D.orders.filter(o=>new Date(o.d).toDateString()==new Date().toDateString()&&o.st!='Cancelled');
const vs=D.prods.flatMap(p=>p.v.map(v=>v.s<=v.low?v.s:null)).filter(x=>x!==null),first={};D.orders.forEach(o=>first[o.phone]=first[o.phone]||o.d);
const g={};lv.forEach(o=>{const k=R>31?o.d.slice(0,7):o.d.slice(5,10);g[k]=(g[k]||0)+o.tot});const ks=Object.keys(g).sort(),mx=Math.max(1,...ks.map(k=>g[k]));
const cs={},ps={};lv.forEach(o=>o.items.forEach(i=>{cs[i.c]=(cs[i.c]||0)+i.price*i.q;ps[i.n]=ps[i.n]||[0,0];ps[i.n][0]+=i.q;ps[i.n][1]+=i.price*i.q}));const cm=Math.max(1,...Object.values(cs));
const sc={};D.orders.forEach(o=>sc[o.st]=(sc[o.st]||0)+1);
return`<h2>Dashboard</h2><div class=bar><select onchange="R=+this.value;render()">${[[1,'Today'],[7,'Last 7 days'],[30,'Last 30 days'],[90,'Last 3 months'],[180,'Last 6 months'],[365,'This year']].map(r=>`<option value=${r[0]} ${R==r[0]?'selected':''}>${r[1]}</option>`).join('')}</select><button class="btn sm" onclick="xl(D.orders)">⬇ Export all to Excel</button></div>
<div class=kp><div><small>Today's orders</small><b>${td.length}</b></div><div><small>Today's revenue</small><b>${fm(td.reduce((a,o)=>a+o.tot,0))}</b></div><div><small>Orders (range)</small><b>${lv.length}</b></div><div><small>Revenue (range)</small><b>${fm(rev)}</b></div><div><small>Avg order value</small><b>${fm(rev/(lv.length||1))}</b></div><div><small>Products sold</small><b>${lv.reduce((a,o)=>a+o.items.reduce((s,i)=>s+i.q,0),0)}</b></div><div><small>New customers</small><b>${Object.values(first).filter(d=>new Date(d)>=new Date(Date.now()-R*864e5)).length}</b></div><div><small>Cancelled</small><b>${os.length-lv.length}</b></div><div><small>Pending orders</small><b>${D.orders.filter(o=>o.st=='Pending').length}</b></div><div><small>Low / out of stock</small><b>${vs.length}</b></div><div><small>Customers</small><b>${Object.keys(first).length}</b></div><div><small>Total revenue</small><b>${fm(live().reduce((a,o)=>a+o.tot,0))}</b></div></div>
<div class=two><div class=sec><b>Revenue</b><div class=bars>${ks.map(k=>`<div title="${k}: ${fm(g[k])}"><i style="height:${g[k]/mx*80}%"></i>${ks.length<16?k.slice(-5):''}</div>`).join('')||'<p>No orders in this range.</p>'}</div></div><div class=sec><b>Order status</b>${Object.entries(sc).map(([k,v])=>`<div class=hb><span>${k}</span><i style="width:${v/D.orders.length*100}%"></i>${v}</div>`).join('')}</div></div>
<div class=two><div class=sec><b>Sales by category</b>${Object.entries(cs).map(([k,v])=>`<div class=hb><span>${k}</span><i style="width:${v/cm*100}%"></i>${Math.round(v/lv.reduce((a,o)=>a+o.sub,0)*100)}%</div>`).join('')}</div><div class=sec><b>Best sellers</b><div class=tw><table>${Object.entries(ps).sort((a,b)=>b[1][1]-a[1][1]).slice(0,6).map(([k,v])=>`<tr><td>${k}</td><td>${v[0]}</td><td>${fm(v[1])}</td></tr>`).join('')}</table></div></div></div>
<div class=sec><b>Recent orders</b> <a style="float:right;cursor:pointer;color:var(--g)" onclick="go('admin/orders')">View all →</a>${otab(D.orders.slice(-10).reverse())}</div>`}
const otab=l=>`<div class=tw><table><tr><th>Order</th><th>Customer</th><th>Date</th><th>Amount</th><th>Payment</th><th>Status</th><th>Tracking</th><th></th></tr>${l.map(o=>`<tr><td>${o.no}</td><td>${o.cust}<br><small>${o.phone}</small></td><td>${new Date(o.d).toLocaleDateString('en-IN')}</td><td>${fm(o.tot)}</td><td>${o.pay}</td><td><span class="pill ${o.st=='Cancelled'?'r':o.st=='Pending'?'w1':''}">${o.st}</span></td><td>${o.track||'–'}</td><td><button class="btn sm" onclick="od('${o.no}')">View</button></td></tr>`).join('')||'<tr><td colspan=8>No orders yet.</td></tr>'}</table></div>`;
let OF={q:'',s:''};
function aOrders(){const l=D.orders.filter(o=>(!OF.q||(o.no+o.cust+o.phone).toLowerCase().includes(OF.q.toLowerCase()))&&(!OF.s||o.st==OF.s)).reverse();return`<h2>Orders</h2><div class=bar><input placeholder="Order no / name / phone" value="${OF.q}" onchange="OF.q=this.value;render()"><select onchange="OF.s=this.value;render()"><option value="">All status</option>${ST.map(s=>`<option ${OF.s==s?'selected':''}>${s}</option>`).join('')}</select><button class="btn sm" onclick="xl(window.__l)">⬇ Export to Excel</button></div><div class=sec>${(window.__l=l,otab(l))}</div>`}
function od(no){const o=D.orders.find(x=>x.no==no);modal(`<h2>${o.no}</h2><p>${o.cust} · ${o.phone}<br>${o.email}<br>${o.addr}</p>${o.items.map(i=>`<div>${i.q}× ${i.n} — ${fm(i.price*i.q)}</div>`).join('')}<p><b>Total ${fm(o.tot)}</b> <small>(ship ${fm(o.ship)}, disc ${fm(o.disc)})</small></p><label>Order status</label><select id=os>${ST.map(s=>`<option ${o.st==s?'selected':''}>${s}</option>`).join('')}</select><label>Payment status</label><select id=ops>${PAY.map(s=>`<option ${o.pay==s?'selected':''}>${s}</option>`).join('')}</select><label>India Post tracking number</label><input id=ot value="${o.track}" placeholder="EE123456789IN"><div class=bar><button class=btn onclick="so('${no}')">Save</button><button class="btn o sm" onclick="navigator.clipboard.writeText($('#ot').value);toast('Copied')">Copy tracking</button><button class="btn gd sm" onclick="trk($('#ot').value)">Open India Post</button><button class="btn o sm" onclick="inv('${no}')">Invoice</button></div>`)}
function so(no){api('/api/admin/orders/'+encodeURIComponent(no),{method:'PATCH',body:{st:$('#os').value,pay:$('#ops').value,track:$('#ot').value.trim()}}).then(()=>{D.stale=1;cl();render();toast('Order updated')}).catch(e=>toast(e.message))}
function inv(no){const o=D.orders.find(x=>x.no==no);modal(`<div id=inv><h2>TAX INVOICE</h2><b>Venkata Sai Dry Fruits (VSD)</b><br>D.No. 23-6-15, Opp: Axis Bank, Patnam Bazar, Guntur – 522003<br>GSTIN 37BRLPK9740E1ZG · 88853 55666<hr><b>Invoice:</b> INV-${o.no.slice(4)} · <b>Order:</b> ${o.no}<br><b>Date:</b> ${new Date(o.d).toLocaleDateString('en-IN')}<br><b>Bill to:</b> ${o.cust}, ${o.addr}<table><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${o.items.map(i=>`<tr><td>${i.n}</td><td>${i.q}</td><td>${fm(i.price)}</td><td>${fm(i.price*i.q)}</td></tr>`).join('')}</table><p>Subtotal ${fm(o.sub)} · Discount ${fm(o.disc)} · Shipping ${fm(o.ship)}<br><b>Grand total ${fm(o.tot)}</b><br>Payment: ${o.pm} (${o.pay})</p></div><button class=btn onclick=print()>🖨 Print / Save as PDF</button>`)}
function xl(l){if(!window.XLSX)return toast('Excel library not loaded (check connection)');const h=['Order ID','Order Date','Customer','Phone','Email','Address','Products','Quantity','Subtotal','Discount','Shipping','Total','Payment Method','Payment Status','Order Status','India Post Tracking'],r=l.map(o=>[o.no,new Date(o.d).toLocaleDateString('en-IN'),o.cust,o.phone,o.email,o.addr,o.items.map(i=>i.n).join('; '),o.items.reduce((a,i)=>a+i.q,0),o.sub,o.disc,o.ship,o.tot,o.pm,o.pay,o.st,o.track]),ws=XLSX.utils.aoa_to_sheet([h,...r]);ws['!cols']=h.map((x,i)=>({wch:i==5||i==6?40:16}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Orders');XLSX.writeFile(wb,'VSD-Orders-'+new Date().toISOString().slice(0,7)+'.xlsx')}
function aProds(){return`<h2>Products</h2><div class=bar><button class=btn onclick="pf(0)">+ Add product</button></div><div class=sec><div class=tw><table><tr><th></th><th>Name</th><th>Category</th><th>Variants</th><th>Stock</th><th>Status</th><th></th></tr>${D.prods.map(p=>`<tr><td class=tn style=font-size:26px>${ev(p)}</td><td>${p.n}</td><td>${p.c}</td><td>${p.v.map(v=>v.w+' '+fm(v.p)).join(', ')}</td><td>${p.v.map(v=>v.s<=0?'<span class=no>OUT</span>':v.s<=v.low?'<span class=low>LOW '+v.s+'</span>':v.s).join(' / ')}</td><td><span class="pill ${p.on?'':'r'}">${p.on?'Active':'Hidden'}</span></td><td><button class="btn sm" onclick="pf(${p.id})">Edit</button> <button class="btn o sm" onclick="pt(${p.id})">${p.on?'Hide':'Show'}</button> <button class="btn rd sm" onclick="pdel(${p.id})">Delete</button></td></tr>`).join('')||'<tr><td>No products found.</td></tr>'}</table></div></div>`}
function pf(id){const p=id?P(id):{n:'',c:D.cats[0][0],e:'🌰',v:[{w:'250g',mrp:0,p:0,s:0,low:10}],f:0};IMG=p.img||'';modal(`<h2>${id?'Edit':'Add'} product</h2><label>Product photo</label><div class=bar><div class=im id=fp style="width:76px;height:76px;font-size:34px">${ev(p)}</div><input type=file accept="image/*" onchange="up(this,'fp')"></div><label>Name</label><input id=fn value="${p.n}"><div class=bar><div style=flex:1><label>Category</label><select id=fc>${D.cats.map(c=>`<option ${p.c==c[0]?'selected':''}>${c[0]}</option>`).join('')}</select></div><div style=flex:1><label>Emoji / icon</label><input id=fe value="${p.e}"></div></div><label>Variants — one per line: weight, MRP, price, stock, low-stock limit (stock of existing sizes is changed in Inventory)</label><textarea id=fv rows=5>${p.v.map(v=>[v.w,v.mrp,v.p,v.s,v.low].join(', ')).join('\n')}</textarea><label style=display:flex;gap:6px><input type=checkbox id=ff style=width:auto ${p.f?'checked':''}>Featured</label><button class=btn onclick="ps(${id})">Save</button>`)}
function ps(id){const v=$('#fv').value.split('\n').map(l=>l.split(',').map(x=>x.trim())).filter(a=>a[0]).map(a=>({w:a[0],mrp:+a[1]||0,p:+a[2]||0,s:Math.max(0,+a[3]||0),low:+a[4]||0}));if(!$('#fn').value.trim()||!v.length||v.some(x=>!x.p))return toast('Enter a name and valid variants');const o={n:$('#fn').value.trim(),c:$('#fc').value,e:$('#fe').value||'📦',f:$('#ff').checked?1:0,v,img:IMG};id?Object.assign(P(id),o):D.prods.push({id:D.pid++,on:1,...o});save();cl();render();toast('Saved')}
const pt=id=>{P(id).on=P(id).on?0:1;save();render()},pdel=id=>{if(D.combos.some(c=>c.items.some(i=>i[0]==id)))return toast('Used in a combo – hide it instead');if(confirm('Delete this product?')){D.prods=D.prods.filter(p=>p.id!=id);save();render()}};
function aCombos(){return`<h2>Combos</h2><div class=bar><button class=btn onclick="cf(0)">+ Create combo</button></div><div class=sec><div class=tw><table><tr><th></th><th>Name</th><th>Contains</th><th>MRP</th><th>Price</th><th>Available</th><th></th></tr>${D.combos.map(c=>`<tr><td class=tn style=font-size:26px>${ev(c)}</td><td>${c.n}</td><td>${c.items.map(([p,v,q])=>q+'×'+P(p).n.split(' ')[0]+' '+P(p).v[v].w).join(', ')}</td><td>${fm(cmrp(c))}</td><td>${fm(c.p)}</td><td>${cav(c)}</td><td><button class="btn sm" onclick="cf(${c.id})">Edit</button> <button class="btn o sm" onclick="D.combos.find(x=>x.id==${c.id}).on^=1;save();render()">${c.on?'Hide':'Show'}</button> <button class="btn rd sm" onclick="if(confirm('Delete?')){D.combos=D.combos.filter(x=>x.id!=${c.id});save();render()}">Del</button></td></tr>`).join('')||'<tr><td>No combos yet.</td></tr>'}</table></div></div>`}
function cf(id){const c=id?CB(id):{n:'',e:'🧺',p:0,items:[]};IMG=c.img||'';modal(`<h2>${id?'Edit':'Create'} combo</h2><label>Combo photo</label><div class=bar><div class=im id=cp style="width:76px;height:76px;font-size:34px">${ev(c)}</div><input type=file accept="image/*" onchange="up(this,'cp')"></div><label>Name</label><input id=cname value="${c.n}"><div class=bar><div style=flex:1><label>Combo price ₹</label><input id=cprice type=number value="${c.p}"></div><div style=flex:1><label>Emoji</label><input id=cem value="${c.e}"></div></div><label>Products inside (set quantity; pick variant)</label>${D.prods.map(p=>{const it=c.items.find(i=>i[0]==p.id);return`<div class=bar style=margin:4px 0><span style=flex:1>${p.e} ${p.n}</span><select class=cv data-p=${p.id}>${p.v.map((v,i)=>`<option value=${i} ${it&&it[1]==i?'selected':''}>${v.w}</option>`).join('')}</select><input class=cqq data-p=${p.id} type=number min=0 value="${it?it[2]:0}" style=width:64px></div>`}).join('')}<button class=btn onclick="cs2(${id})">Save combo</button>`)}
function cs2(id){const items=[...document.querySelectorAll('.cqq')].map(i=>[+i.dataset.p,+document.querySelector(`.cv[data-p="${i.dataset.p}"]`).value,+i.value]).filter(x=>x[2]>0),o={n:$('#cname').value.trim(),p:+$('#cprice').value,e:$('#cem').value||'🧺',items,img:IMG};if(!o.n||!o.p||!items.length)return toast('Add a name, price and at least one product');id?Object.assign(CB(id),o):D.combos.push({id:D.cid++,on:1,f:1,...o});save();cl();render()}
let IF='';
function aInv(){const rows=D.prods.flatMap(p=>p.v.map((v,i)=>({p,v,i,st:v.s<=0?'Out of Stock':v.s<=v.low?'Low Stock':'Healthy'}))).filter(r=>!IF||r.st==IF);return`<h2>Inventory</h2><div class=bar><select onchange="IF=this.value;render()"><option value="">All</option><option ${IF=='Healthy'?'selected':''}>Healthy</option><option ${IF=='Low Stock'?'selected':''}>Low Stock</option><option ${IF=='Out of Stock'?'selected':''}>Out of Stock</option></select></div><div class=sec><div class=tw><table><tr><th>Product</th><th>Variant</th><th>Stock</th><th>Low limit</th><th>Status</th></tr>${rows.map(r=>`<tr><td>${r.p.n}</td><td>${r.v.w}</td><td><input type=number min=0 value=${r.v.s} style=width:80px onchange="setS(${r.p.id},${r.i},+this.value)"></td><td>${r.v.low}</td><td><span class="pill ${r.st=='Healthy'?'':r.st=='Low Stock'?'w1':'r'}">${r.st=='Healthy'?'Healthy Stock':r.st.toUpperCase()}</span></td></tr>`).join('')||'<tr><td>No low stock products.</td></tr>'}</table></div></div><h3 style=margin:16px 0>Inventory log</h3><div class=sec>${D.log.slice(0,10).map(l=>`<div><small>${new Date(l[0]).toLocaleString('en-IN')} · admin</small> ${l[1]}</div>`).join('')||'No changes yet.'}</div>`}
function setS(id,i,n){api('/api/admin/stock',{method:'POST',body:{id,vi:i,s:Math.max(0,Math.floor(n))}}).then(()=>{D.stale=1;render();toast('Stock updated')}).catch(e=>toast(e.message))}

/** Theme picker: four colour schemes for the customer website. */
function aTheme(){const cur=D.theme||'green';return`<h2>Website theme</h2><p>Choose the colour scheme for the customer website. It applies instantly.</p><div class=kp style="grid-template-columns:repeat(auto-fit,minmax(210px,1fr))">${THEMES.map(t=>`<div style="cursor:pointer;border-top:4px solid ${t[2]}" onclick="setTheme('${t[0]}')"><b style="font-size:20px">${t[1]}</b><div style="display:flex;gap:8px;margin:12px 0"><i style="width:44px;height:44px;border-radius:50%;background:${t[2]}"></i><i style="width:44px;height:44px;border-radius:50%;background:${t[3]}"></i></div>${cur==t[0]?'<span class=pill>Active</span>':'<small>Click to apply</small>'}</div>`).join('')}</div>`}

/* ---- Banners ---- */
function aBanners(){return`<h2>Banners</h2><div class=bar><button class=btn onclick="bf(0)">+ Add banner</button><small>Live banners rotate on the home page every 5 seconds.</small></div><div class=sec><div class=tw><table><tr><th>Image</th><th>Heading</th><th>Button → link</th><th>Status</th><th></th></tr>${D.banners.map(b=>`<tr><td class=tn>${ev({img:b.img,e:'🖼️'})}</td><td>${b.h}</td><td>${b.btn||'–'} → ${b.link||'–'}</td><td><span class="pill ${b.on?'':'r'}">${b.on?'Live':'Hidden'}</span></td><td><button class="btn sm" onclick="bf(${b.id})">Edit</button> <button class="btn o sm" onclick="bt(${b.id})">${b.on?'Hide':'Show'}</button> <button class="btn rd sm" onclick="bdel(${b.id})">Delete</button></td></tr>`).join('')||'<tr><td>No banners yet.</td></tr>'}</table></div></div>`}
function bf(id){const b=id?D.banners.find(x=>x.id==id):{k:'',h:'',d:'',btn:'Shop Now',link:'shop',img:'',on:1};IMG=b.img||'';modal(`<h2>${id?'Edit':'Add'} banner</h2><label>Banner image (wide photo, around 1200×600)</label><div class=bar><div class=im id=bp style="width:150px;height:90px;font-size:30px">${ev({img:b.img,e:'🖼️'})}</div><input type=file accept="image/*" onchange="up(this,'bp',1000)"></div><label>Small tag line</label><input id=bnk value="${b.k}"><label>Heading</label><input id=bnh value="${b.h}"><label>Description</label><textarea id=bnd rows=2>${b.d}</textarea><div class=bar><div style=flex:1><label>Button text</label><input id=bnb value="${b.btn}"></div><div style=flex:1><label>Button link</label><input id=bnl value="${b.link}"></div></div><small>Link examples: shop · shop/Combos · shop/Nuts · https://…</small><label style=display:flex;gap:6px><input type=checkbox id=bno style=width:auto ${b.on?'checked':''}>Show on website</label><p><button class=btn onclick="bs(${id})">Save banner</button></p>`)}
function bs(id){const o={k:$('#bnk').value,h:$('#bnh').value.trim(),d:$('#bnd').value,btn:$('#bnb').value,link:$('#bnl').value.trim(),img:IMG,on:$('#bno').checked?1:0};if(!o.h)return toast('Enter a heading');id?Object.assign(D.banners.find(x=>x.id==id),o):D.banners.push({id:D.bid++,...o});save();cl();render();toast('Banner saved')}
const bt=id=>{const b=D.banners.find(x=>x.id==id);b.on=b.on?0:1;save();render()},bdel=id=>{if(confirm('Delete this banner?')){D.banners=D.banners.filter(x=>x.id!=id);save();render()}};
/* ---- Settings: shipping, WhatsApp number, scrolling strip ---- */
function aSettings(){const s=D.settings;return`<h2>Settings</h2><div class=sec><b>Shipping</b><div class=bar><div><label>Shipping charge (₹)</label><input id=sShip type=number min=0 value="${s.ship}"></div><div><label>Free shipping above (₹)</label><input id=sFree type=number min=0 value="${s.free}"></div></div><b>WhatsApp orders</b><label>WhatsApp number (with country code)</label><input id=sWa value="${s.wa}" style=max-width:260px><label>Scrolling text in the top strip</label><textarea id=sTick rows=2>${s.ticker}</textarea><p><button class=btn onclick=saveSet()>Save settings</button></p></div>`}
function saveSet(){const s=D.settings,n=$('#sWa').value.replace(/\D/g,'');s.ship=Math.max(0,+$('#sShip').value||0);s.free=Math.max(0,+$('#sFree').value||0);s.wa=n.length==10?'91'+n:(n||s.wa);s.ticker=$('#sTick').value.trim()||s.ticker;save();render();toast('Settings saved')}
